set(_CATKIN_CURRENT_PACKAGE "a_robot_platform")
set(a_robot_platform_VERSION "0.1.0")
set(a_robot_platform_MAINTAINER "zw <zw@todo.todo>")
set(a_robot_platform_PACKAGE_FORMAT "1")
set(a_robot_platform_BUILD_DEPENDS "roscpp" "geometry_msgs" "nav_msgs" "sensor_msgs" "std_msgs" "tf")
set(a_robot_platform_BUILD_EXPORT_DEPENDS "roscpp" "geometry_msgs" "nav_msgs" "sensor_msgs" "std_msgs" "tf")
set(a_robot_platform_BUILDTOOL_DEPENDS "catkin")
set(a_robot_platform_BUILDTOOL_EXPORT_DEPENDS )
set(a_robot_platform_EXEC_DEPENDS "roscpp" "geometry_msgs" "nav_msgs" "sensor_msgs" "std_msgs" "tf")
set(a_robot_platform_RUN_DEPENDS "roscpp" "geometry_msgs" "nav_msgs" "sensor_msgs" "std_msgs" "tf")
set(a_robot_platform_TEST_DEPENDS )
set(a_robot_platform_DOC_DEPENDS )
set(a_robot_platform_DEPRECATED "")