# CMake generated Testfile for 
# Source directory: /home/shenyu/distributed_robot_sys/src/amcl
# Build directory: /home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/amcl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(_ctest_amcl_rostest_test_set_initial_pose.xml "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results/amcl/rostest-test_set_initial_pose.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/shenyu/distributed_robot_sys/src/amcl --package=amcl --results-filename test_set_initial_pose.xml --results-base-dir \"/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results\" /home/shenyu/distributed_robot_sys/src/amcl/test/set_initial_pose.xml ")
ADD_TEST(_ctest_amcl_rostest_test_set_initial_pose_delayed.xml "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results/amcl/rostest-test_set_initial_pose_delayed.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/shenyu/distributed_robot_sys/src/amcl --package=amcl --results-filename test_set_initial_pose_delayed.xml --results-base-dir \"/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results\" /home/shenyu/distributed_robot_sys/src/amcl/test/set_initial_pose_delayed.xml ")
ADD_TEST(_ctest_amcl_rostest_test_basic_localization_stage.xml "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results/amcl/rostest-test_basic_localization_stage.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/shenyu/distributed_robot_sys/src/amcl --package=amcl --results-filename test_basic_localization_stage.xml --results-base-dir \"/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results\" /home/shenyu/distributed_robot_sys/src/amcl/test/basic_localization_stage.xml ")
ADD_TEST(_ctest_amcl_rostest_test_small_loop_prf.xml "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results/amcl/rostest-test_small_loop_prf.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/shenyu/distributed_robot_sys/src/amcl --package=amcl --results-filename test_small_loop_prf.xml --results-base-dir \"/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results\" /home/shenyu/distributed_robot_sys/src/amcl/test/small_loop_prf.xml ")
ADD_TEST(_ctest_amcl_rostest_test_small_loop_crazy_driving_prg.xml "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results/amcl/rostest-test_small_loop_crazy_driving_prg.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/shenyu/distributed_robot_sys/src/amcl --package=amcl --results-filename test_small_loop_crazy_driving_prg.xml --results-base-dir \"/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results\" /home/shenyu/distributed_robot_sys/src/amcl/test/small_loop_crazy_driving_prg.xml ")
ADD_TEST(_ctest_amcl_rostest_test_texas_greenroom_loop.xml "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results/amcl/rostest-test_texas_greenroom_loop.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/shenyu/distributed_robot_sys/src/amcl --package=amcl --results-filename test_texas_greenroom_loop.xml --results-base-dir \"/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results\" /home/shenyu/distributed_robot_sys/src/amcl/test/texas_greenroom_loop.xml ")
ADD_TEST(_ctest_amcl_rostest_test_rosie_multilaser.xml "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results/amcl/rostest-test_rosie_multilaser.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/shenyu/distributed_robot_sys/src/amcl --package=amcl --results-filename test_rosie_multilaser.xml --results-base-dir \"/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results\" /home/shenyu/distributed_robot_sys/src/amcl/test/rosie_multilaser.xml ")
ADD_TEST(_ctest_amcl_rostest_test_texas_willow_hallway_loop.xml "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results/amcl/rostest-test_texas_willow_hallway_loop.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/shenyu/distributed_robot_sys/src/amcl --package=amcl --results-filename test_texas_willow_hallway_loop.xml --results-base-dir \"/home/shenyu/distributed_robot_sys/build-src-Desktop-Debug/test_results\" /home/shenyu/distributed_robot_sys/src/amcl/test/texas_willow_hallway_loop.xml ")
